#!/bin/bash

# superuser name of remote pc (supposed that all clients have same superuser)
shared_username="scom"
# new username you want to create
username=""
# The first and second parts of IP address (third and last parts are specified at `hostnames`)
network="10.158.233."
# passward of superuser at remote pc (supposed that all clients have same passward)
pswd=
# passward of server pc
server_pswd=

# used for `auto_sshkey.sh`
hostnames_ids=(
	"host1 01"
  "host2 02"
)
